imag/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

imagazine/cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('add/<int:id>/', AddProductCartView.as_view(), name='add'),
    path('remove/<int:id>/', RemoveProductCart.as_view(), name='remove'),
    path('', IndexCart.as_view(), name='index'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('payment/api/', YoomoneyNotifView.as_view(), name='notif'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('orders/<int:pk>/', OrderView.as_view(), name='order')
]

imagazine/goods/urls.py
from django.urls import path, include
from imagazine.goods.views import *

urlpatterns = [ 
               path('', IndexView.as_view(), name='main'),
               path('games/', GamesIndexView.as_view(), name='index'),
               path('console/', ConsolesView.as_view(), name='consoles_index'),
               path('console/<int:pk>/', ConsoleView.as_view(), name='console'),
               path('games/<int:pk>/', ProfileGameView.as_view(), name='profile'),
               path('love/<int:pk>/', LoveIndexView.as_view(), name='loves'), 
               path('love/remove/<int:pk>/<int:id>/', RemoveLoveView.as_view(), name='remove_love'),
               path('love/add/<int:pk>/<int:id>/', LoveAddView.as_view(), name='add_love')
               ]

imagazine/urls.py
from django.contrib import admin
from django.urls import path, include
from imagazine.views import MainView, AboutView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('users/', include(('imagazine.users.urls', 'users'), namespace='users')),
    path('goods/', include(('imagazine.goods.urls', 'goods'), namespace='goods')),
    path('cart/', include(('imagazine.cart.urls', 'cart'), namespace='cart'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #new

imagazine/cart/models.py
from django.db import models
from imagazine.users.models import User
from imagazine.goods.models import Goods

class Order(models.Model):
    order_id = models.CharField(max_length=100, unique=True)
    customer = models.ForeignKey(User, on_delete = models.CASCADE, related_name='orders')
    payment = models.CharField(max_length=50, blank=True, null=True)
    price = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(null=True, blank=True)
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete = models.CASCADE, related_name='items')
    product = models.ForeignKey(Goods, on_delete = models.CASCADE)
    count = models.PositiveIntegerField()

imagazine/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CatrAddForm(forms.Form):
    count = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, initial=1, label='', required=False)
    
    def clean(self):
        cleaned_data = super().clean()
        for key, value in cleaned_data.items():
            if key == 'count' and type(value) != int:
                cleaned_data[key] = self.initial[key]
        return cleaned_data

imagazine/cart/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import CatrAddForm
from .cart import Cart
from django.shortcuts import get_object_or_404
from django.contrib import messages
from imagazine.goods.models import Goods
from yookassa import Configuration, Payment
from imagazine.settings import *
from django.urls import reverse_lazy
import uuid
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import ensure_csrf_cookie
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import *
from django.core.mail import send_mail
from imagazine.cart.mixins import RightUserMixinOrder
from django.views.generic import DetailView
from imagazine.coupons.forms import CouponForm
from imagazine.coupons.models import Coupons
from datetime import datetime as dtim

Configuration.account_id = YOOKASSA_SHOP_ID
Configuration.secret_key = YOOKASSA_SECRET_KEY

def avaliable_item(cart, product, cd={'count': 0}):
    if cart.cart.get(str(product.id), False):
        if cd['count'] + cart.cart[str(product.id)]['count'] > product.count:
            return False
        return True
    elif cd['count'] > product.count:
        return False
    return True

def avaliable_cart(cart):
    lst = list()
    for k, v in cart.cart.items():
        product = get_object_or_404(Goods, id=k)
        lst.append(avaliable_item(cart, product))
    return all(lst)



# Create your views here.
class AddProductCartView(View):
    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        product = get_object_or_404(Goods, id=kwargs['id'])
        form = CatrAddForm(request.POST, initial={'count': 1})
        if form.is_valid():
            cd = form.clean()
            if avaliable_item(cart, product, cd):
                cart.add(product, cd['count'])
                messages.success(request, 'Товар добавлен в корзину успешно')
            else:
                messages.error(request, 'Товара нет в таком количестве')
        else:
            messages.error(request, 'Товар не добавлен в корзину')
        return redirect('cart:index')
    
class RemoveProductCart(View):
    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        product = get_object_or_404(Goods, id=kwargs['id'])
        cart.remove(product)
        return redirect('cart:index')
    
class IndexCart(View):
    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        d = dict()
        for i, v in cart.cart.items():
            d[Goods.objects.get(id=i).get_model()] = {'count': v['count'], 'price': v['price']}
        return render(request, 'cart/index.html', {'cart': d, 'cart_': cart, 'form': CatrAddForm, 'form_p': CouponForm(initial={'coupon': request.session.get('code', '')})})
    
    def post(self, request, *args, **kwargs):
        form = CouponForm(request.POST)
        if form.is_valid():
            coupon = form.cleaned_data['coupon']
            datetime = dtim.now()
            try:
                c = Coupons.objects.get(code=coupon, valid_from__lte=datetime, valid_to__gte=datetime, active=True)
                discount = c.discount
                cart = Cart(request)
                cart.discount(discount)
                request.session['code'] = coupon
            except:
                messages.error(request, 'Нет такого промокода')
        
        return redirect('cart:index')
    
class PaymentView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')
    
    def get(self, request, *args, **kwargs):
        idempotence_key = str(uuid.uuid4())
        cart = Cart(request)
        if avaliable_cart(cart):
            lst = list()
            for product_id, count_price in cart.cart.items():
                d = dict()
                d["description"] = get_object_or_404(Goods, id=product_id).name
                d["quantity"] = count_price['count']
                d['amount'] = {"value": count_price['price'] - (cart.session['discount'] / 100) * count_price['price'], "currency": "RUB"}
                d.update({"vat_code": "2",
                "payment_mode": "full_prepayment",
                "payment_subject": "commodity"})
                lst.append(d)
                
            payment = Payment.create({
                "amount": {
                "value": str(cart.price()),
                "currency": "RUB"
                },
                "receipt": {
                    "customer": {
                            "email": request.user.email
                },
                     "items": lst
    },
                "payment_method_data": {
                "type": "bank_card"
                },
                "confirmation": {
                "type": "redirect",
                "return_url": 'https://0ca1-79-139-191-0.ngrok-free.app'+ str(reverse_lazy('main'))
                },
                "capture": False,
                "description": "Заказ в Imag"
            }, idempotence_key)

            # get confirmation url
            confirmation_url = payment.confirmation.confirmation_url
            
            # модель заказа
            order = Order.objects.create(order_id=payment.id, customer=request.user, payment='no')
            for product_id, count_price in cart.cart.items():
                product = get_object_or_404(Goods, id=product_id)
                count = count_price['count']
                OrderItem.objects.create(order=order, product=product, count=count)
                
            order.price = int(payment['amount']['value'][:-3])
            order.created_at = payment['created_at']
            order.save()
            cart.clear_cart()
            return HttpResponseRedirect(confirmation_url)
        else:
            messages.error(request, 'Товара уже нет в таком количестве')
            return redirect('cart:index')
    
    
class YoomoneyNotifView(APIView):
    '''сюда приходит уведомление о том, что денбги переведены и дальше идет логика приложения'''
    def post(self, request):
        payment_id = request.data['object']['id']
        order = Order.objects.get(order_id=payment_id)
        for item in order.items.all():
            if item.count > item.product.count:
                response = Payment.cancel(payment_id, str(uuid.uuid4()))
                return Response(response, status=200)
            else:
                product = item.product
                product.count = product.count - item.count
                product.save()
        Payment.capture(payment_id)
        order.payment = 'yes'
        order.save()
        send_mail(
            f'Чек Imag {payment_id}',
            'Заказ оплачен и принят в магазине. Вы можете просмотреть его в соответсвующем поле "Заказы". Если возникли какие-то проблемы - напишите на почту faridylkaaa@yandex.ru',
            'faridylkaaa@yandex.ru',
            recipient_list=[order.customer.email],
            fail_silently=False
        )
        return Response(status=200)
    
class OrdersView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        orders = user.orders.filter(payment='yes').order_by('-created_at')
        return render(request, 'cart/orders.html', {'orders': orders})
    
class OrderView(RightUserMixinOrder, DetailView):
    context_object_name = 'order'
    template_name = 'cart/order_profile.html'
    model = Order
    
    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['title'] = 'Заказ №'+str(content['order'].id)
        content['count'] = sum(item.count for item in content['order'].items.all())
        return content

templates/cart/index.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block nav_cart%}
active 
{% endblock %}

{% block full_content %}
<section class="pt-5 pb-5">
    <div class="container">
      <div class="row w-100">
          <div class="col-lg-12 col-md-12 col-12">
              <h3 class="display-5 mb-2 text-center">Корзина товаров</h3>
              <p class="mb-5 text-center">
                  <i class="text-info font-weight-bold">{{ cart_.len }}</i> товаров в корзине</p>
                  {% if cart_.len == 0 %}
                  <h1>
                    В вашей корзине нет товаров
                  </h1>
                  {% else %}
              <table id="shoppingCart" class="table table-condensed table-responsive">
                  <thead>
                      <tr>
                          <th style="width:60%">Товар</th>
                          <th style="width:12%">Цена</th>
                          <th style="width:10%">Количество</th>
                          <th style="width:16%"></th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for product, v in cart.items %}
                      <tr>
                          <td data-th="Product">
                              <div class="row">
                                  <div class="col-md-3 text-left">
                                      <img src="{{ product.photos.first.image.url }}" alt="" class="img-fluid d-none d-md-block rounded mb-2 shadow ">
                                  </div>
                                  <div class="col-md-9 text-left mt-sm-2">
                                    {% if product.is_game %}
                                      <h4><a href='{% url "goods:profile" pk=product.id %}'>{{ product.name }}</a></h4>
                                      {% else %}
                                      <h4><a href='{% url "goods:console" pk=product.id %}'>{{ product.name }}</a></h4>
                                      {% endif %}
                                      <p class="font-weight-light"></p>
                                  </div>
                              </div>
                          </td>
                          <td data-th="Price">{{ product.price }}₽</td>
                          <td data-th="Quantity">
                            {{v.count}}
                          </td>
                          <td class="actions" data-th="">
                              <div class="text-right">
                                
                                  <form action="{% url "cart:remove" id=product.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-white border-secondary bg-white btn-md mb-2">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                              </div>
                          </td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
              <div class="float-right text-right">
                <form method="post">
                    {% csrf_token %}
                    {{ form_p }}
                    <input type="submit" class="btn btn-primary" value="Применить" style="margin: 10px; margin-left: 0px">
                </form>
                  <h4>Итог: ( с учётом скидок )</h4>
                  <h1>{{ cart_.get_total_price }}₽</h1>
              </div>
          </div>
      </div>
      <div class="row mt-4 d-flex align-items-center">
          <div class="col-sm-6 order-md-2 text-right">
              <a href="{% url "cart:payment" %}" class="btn btn-primary mb-4 btn-lg pl-5 pr-5">Оплата</a>
          </div>
          {% endif %}
          <div class="col-sm-6 mb-3 mb-m-1 order-md-1 text-md-left">
              <a href="{% url "goods:main" %}">
                  <i class="fas fa-arrow-left mr-2"></i> Начать покупки</a>
          </div>
      </div>
  </div>
  </section>
  {% endblock %}

templates/cart/order.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block nav_orders%}
active 
{% endblock %}

templates/cart/order_profile.html
{% extends "cart/order.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block full_content %}
<div>
<h2 style="text-align: center; padding: 5%;">
    Ваш id заказа {{ order.id }}
</h2>
</div>
<table class="table" style="width: 85%; margin: auto;">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Название</th>
        <th scope="col">Цена</th>
        <th scope="col">Количество</th>
      </tr>
    </thead>
    <tbody>
        {% for item in order.items.all %}
      <tr>
        <th scope="row">{{item.product.id}}</th>
        {% if item.product.get_model.is_game %}
        <td><a href="{% url "goods:profile"  pk=item.product.id%}">{{item.product.name}}</a></td>
        {% else %}
        <td><a href="{% url "goods:console"  pk=item.product.id %}">{{item.product.name}}</a></td>
        {% endif %}
        <td>{{item.product.price}}₽</td>
        <td>{{item.count}}</td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
        <tr>
          <td></td>
          <td>ИТОГ с учётом скидок</td>
          <td>{{order.price}}₽</td>
          <td>{{count}}</td>
        </tr>
      </tfoot>
  </table>
  {% endblock %}

templates/cart/orders.html
{% extends "cart/order.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block full_content %}
<div>
<h2 style="text-align: center; padding: 5%;">
    Ваши Заказы
</h2>
</div>
<table class="table" style="width: 85%; margin: auto;">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Номер заказа</th>
        <th scope="col">Цена</th>
        <th scope="col">Дата</th>
      </tr>
    </thead>
    <tbody>
        {% for order in orders %}
      <tr>
        <th scope="row">{{order.id}}</th>
        <td><a href="{% url "cart:order" pk=order.id %}">{{order.order_id}}</a></td>
        <td>{{order.price}}₽</td>
        <td>{{order.created_at}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endblock %}