imag/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

imagazine/cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('add/<int:id>/', AddProductCartView.as_view(), name='add'),
    path('remove/<int:id>/', RemoveProductCart.as_view(), name='remove'),
    path('', IndexCart.as_view(), name='index'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('payment/api/', YoomoneyNotifView.as_view(), name='notif'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('orders/<int:pk>/', OrderView.as_view(), name='order')
]

imagazine/goods/urls.py
from django.urls import path, include
from imagazine.goods.views import *

urlpatterns = [ 
               path('', IndexView.as_view(), name='main'),
               path('games/', GamesIndexView.as_view(), name='index'),
               path('console/', ConsolesView.as_view(), name='consoles_index'),
               path('console/<int:pk>/', ConsoleView.as_view(), name='console'),
               path('games/<int:pk>/', ProfileGameView.as_view(), name='profile'),
               path('love/<int:pk>/', LoveIndexView.as_view(), name='loves'), 
               path('love/remove/<int:pk>/<int:id>/', RemoveLoveView.as_view(), name='remove_love'),
               path('love/add/<int:pk>/<int:id>/', LoveAddView.as_view(), name='add_love')
               ]

imagazine/urls.py
from django.contrib import admin
from django.urls import path, include
from imagazine.views import MainView, AboutView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('users/', include(('imagazine.users.urls', 'users'), namespace='users')),
    path('goods/', include(('imagazine.goods.urls', 'goods'), namespace='goods')),
    path('cart/', include(('imagazine.cart.urls', 'cart'), namespace='cart'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #new

imagazine/goods/models.py
from django.db import models
from imagazine.labels.models import *

class Goods(models.Model):
    name = models.TextField(max_length=250)
    description = models.TextField(max_length=500)
    model_console = models.ForeignKey(ModelConsole, on_delete=models.CASCADE)
    count = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    
    def get_model(self):
        try:
            return self.game
        except:
            return self.console

    
# Create your models here.
class Game(Goods):
    category = models.ManyToManyField(CategoryGame)
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.name
    
    def is_game(self):
        return True
    
class Console(Goods):
    pass
    
    def __str__(self) -> str:
        return self.name
    
    def is_game(self):
        return False

class Gallery(models.Model):
    image = models.ImageField(upload_to='images/goods/console/') # вот тут бы ссылку поменять
    good = models.ForeignKey(Goods, on_delete=models.CASCADE, related_name='photos')

imagazine/goods/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Game, Console
from .filters import GameFilter, ConsoleFilter
from django.http import Http404
from imagazine.cart.forms import CatrAddForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .models import Goods
from imagazine.users.mixins import RightUserMixin
from imagazine.users.models import User
from django.contrib import messages
from django.urls import reverse_lazy

# Create your views here.
class GamesIndexView(ListView):
    filterset_class = GameFilter
    paginate_by = 8
    template_name = 'goods/index.html'
    context_object_name = 'games'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Игры'
        context['filterset'] = self.filterset
        return context
    
    def get_queryset(self):
        queryset = Game.objects.all()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.order_by('-count')
    
class ProfileGameView(DetailView):
    model = Game
    template_name = 'goods/profile.html'
    context_object_name = 'game'
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        content = super().get_context_data(**kwargs)
        content['title'] = content['game'].name
        content['form'] = CatrAddForm
        content['cat'] = '/'.join([name.name for name in content['game'].category.all()])
        return content
    
class IndexView(View):
    def get(self, request, *args, **kwargs):
        form = CatrAddForm
        return render(request, 'goods/category.html', {'form': form})
    
class ConsolesView(ListView):
    context_object_name = 'consoles'
    template_name = 'goods/console.html'
    paginate_by = 8
    filterset_class = ConsoleFilter
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Консоли'
        context['filterset'] = self.filterset
        return context
    
    def get_queryset(self) -> QuerySet[Any]:
        queryset = Console.objects.all()
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        return self.filterset.qs.order_by('-count')
    
class ConsoleView(DetailView):
    context_object_name = 'console'
    template_name = 'goods/profile_console.html'
    model = Console
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        content = super().get_context_data(**kwargs)
        content['form'] = CatrAddForm
        content['title'] = content['console'].name
        return content
    
class LoveAddView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, id=kwargs['pk'])
        product = get_object_or_404(Goods, id=kwargs['id'])
        user.favor.add(product)
        return redirect(reverse_lazy('goods:loves', kwargs={'pk': user.id}))
    
class LoveIndexView(RightUserMixin, View):
    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, id=kwargs['pk'])
        favor = user.favor.all()
        return render(request, 'goods/index_love.html', {'favor': favor, 'len': len(favor)})
    
class RemoveLoveView(RightUserMixin, View):
    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, id=kwargs['pk'])
        favors = user.favor.all()
        favor = get_object_or_404(Goods, id=kwargs['id'])
        if favor in favors:
            user.favor.remove(favor)
        else:
            messages.error(request, 'Товара итак нет в избранном')
        return redirect(reverse_lazy('goods:loves', kwargs={'pk': user.id}))

templates/goods/category.html
{% extends "goods/goods.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block full_content %}
<div class="row sd-6 center" style="align-items: start;">
    <div class="col-12 mb-4">
      <span class="badge bg-pastel-primary text-primary text-uppercase-bold-sm">
        Все категории
      </span>
    </div>

    <!-- Category -->
    <div class="col-md-3 mb-4">
      <a href="{% url "goods:index" %}" class="card align-items-center text-decoration-none border-0 hover-lift-light py-4">
        <span class="icon-circle icon-circle-lg bg-pastel-primary text-primary">
          <img src="https://img.icons8.com/ios/50/ps-controller.png" width="512" height="50" viewBox="0 0 512 512"><title>ionicons-v5-c</title></img>
        </span>
        <span class="text-dark mt-3">
          Игры
        </span>
      </a>
    </div>

    <!-- Category -->
    <div class="col-md-3 mb-4">
      <a href="{% url "goods:consoles_index" %}" class="card align-items-center text-decoration-none border-0 hover-lift-light py-4">
        <span class="icon-circle icon-circle-lg bg-pastel-primary text-primary">
          <img src="https://img.icons8.com/clouds/100/xbox-series-x.png" width="100" height="100" viewBox="0 0 512 512"><title>ionicons-v5-e</title></img>
        </span>
        <span class="text-dark mt-3">
          Консоли
        </span>
      </a>
    </div>
{% endblock %}

templates/goods/console.html
{% extends "goods/goods.html" %}
{% load bootstrap5 %}
{% load bootstrap %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block full_content %}
<section class="section-products">
    <div class="container">
            <div class="row justify-content-center text-center">
                    <div class="col-md-8 col-lg-6">
                            <div class="header">
                                    <h3>лучшие продукты</h3>
                                    <h2>КОНСОЛИ</h2>
                            </div>
                    </div>
            </div>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
            <button class="btn btn-secondary" style="margin-bottom: 20px;">Скрыть/показать фильтр</button>
            <div class="block_with_text" style="display: none;">
                {% if page_obj.number == 1 %}
                {% if filterset.is_bound %}
                <form action="{% url "goods:consoles_index" %}">
                <button type="submit" class="btn btn-info" style="margin:0 10px;">Очистить фильтр</button>
                </form>
                {% endif %}
            <form action="" method="get">
                {{ filterset.form|bootstrap }}
                <input type="submit" class="btn btn-primary" value='Применить' style="margin-top: 20px; margin-bottom: 20px;"/>
              </form>
              {% endif %}

            </div>
                <script type="text/javascript">
                    $('.btn').click(function(){
              $(".block_with_text").fadeToggle(100);
            });  
                </script>
            
            <div class="as-console-wrapper"><div class="as-console"></div></div>
            <div class="row">
                {% if page_obj.paginator.count == 0 %}
                <h1>Похоже, товаров по вашему запросу нет!</h1>
                {% else %}
                {% for console in page_obj %}
                    <!-- Single Product -->
                    <div class="col-md-6 col-lg-4 col-xl-3">
                            <div id="product-1" class="single-product">
                                    <div class="part-1" style="background: url({{console.photos.all.first.image.url}}) no-repeat center;    background-size: contain;
                                    height: 100vh;
                                    background-position: center;
                                    background-repeat: no-repeat;">
                                    {% if console.count == 0 %}
                                    <span class="new">НЕ В НАЛИЧИИ</span>
                                    {% elif console.count <= 3 %}
                                    <span class="discount">МАЛО</span>
                                    {% endif %}
                                            <ul>
                                                    <li>
                                                        <form action="{% url "cart:add" id=console.id %}" method="post">
                                                            {% csrf_token %}
                                                            <button class="btn btn-white bg-white btn-md" style="border-radius: 0;">
                                                            <i class="fas fa-shopping-cart"></i>
                                                            </button>
                                                        </form>
                                                    </li>
                                                    {% if request.user.is_authenticated %}
                                                    <li><form action="{% url "goods:add_love" id=console.id pk=request.user.id %}" method="post">
                                                        {% csrf_token %}
                                                        <button class="btn btn-white bg-white btn-md" style="border-radius: 0;">
                                                        <i class="fas fa-heart"></i>
                                                        </button>
                                                    </form></li>
                                                    {% endif %}
                                                    <li><a href="#"><i class="fas fa-plus"></i></a></li>
                                                    <li><a href="{% url "goods:console" pk=console.id %}"><i class="fas fa-expand"></i></a></li>
                                            </ul>
                                    </div>
                                    <div class="part-2">
                                            <h3 class="product-title"><a href="{% url "goods:console" pk=console.id %}">{{ console.name }}</a></h3>
                                            <h4 class="product-price">{{ console.price }}₽</h4>
                                    </div>
                            </div>
                    </div>
                    {% endfor %}
                    
            </div>
            {% endif %}
    </div>
</section>
{% if page_obj.paginator.count != 0 %}
<nav class="pagination-outer" aria-label="Page navigation">
        <ul class="pagination">
                {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                </a>
            </li>
            {% endif %}
                {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-item active"><a class="page-link" href="?page={{ p }}">{{p}}</a></li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{p}}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                    <span aria-hidden="true">»</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
{% endblock full_content %}

templates/goods/goods.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block nav_goods%}
active 
{% endblock %}

templates/goods/index.html
{% extends "goods/goods.html" %}
{% load bootstrap5 %}
{% load bootstrap %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block full_content %}
<section class="section-products">
    <div class="container">
            <div class="row justify-content-center text-center">
                    <div class="col-md-8 col-lg-6">
                            <div class="header">
                                    <h3>лучшие продукты</h3>
                                    <h2>ИГРЫ</h2>
                            </div>
                    </div>
            </div>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
            <button class="btn btn-secondary" style="margin-bottom: 20px;">Скрыть/показать фильтр</button>
            <div class="block_with_text" style="display: none;">
                {% if page_obj.number == 1 %}
                {% if filterset.is_bound %}
                <form action="{% url "goods:index" %}">
                <button type="submit" class="btn btn-info" style="margin:0 10px;">Очистить фильтр</button>
                </form>
                {% endif %}
            <form action="" method="get">
                {{ filterset.form|bootstrap }}
                <input type="submit" class="btn btn-primary" value='Применить' style="margin-top: 20px; margin-bottom: 20px;"/>
              </form>
              {% endif %}

            </div>
                <script type="text/javascript">
                    $('.btn').click(function(){
              $(".block_with_text").fadeToggle(100);
            });  
                </script>
            
            <div class="as-console-wrapper"><div class="as-console"></div></div>
            <div class="row">
                {% if page_obj.paginator.count == 0 %}
                <h1>Похоже, товаров по вашему запросу нет!</h1>
                {% else %}
                {% for game in page_obj %}
                    <!-- Single Product -->
                    <div class="col-md-6 col-lg-4 col-xl-3">
                            <div id="product-1" class="single-product">
                                    <div class="part-1" style="background: url({{game.photos.all.first.image.url}}) no-repeat center;    background-size: contain;
                                    height: 100vh;
                                    background-position: center;
                                    background-repeat: no-repeat;">
                                    {% if game.count == 0 %}
                                    <span class="new">НЕ В НАЛИЧИИ</span>
                                    {% elif game.count <= 3 %}
                                    <span class="discount">МАЛО</span>
                                    {% endif %}
                                            <ul>
                                                    <li><form action="{% url "cart:add" id=game.id %}" method="post">
                                                        {% csrf_token %}
                                                        <button class="btn btn-white bg-white btn-md" style="border-radius: 0;">
                                                        <i class="fas fa-shopping-cart"></i>
                                                        </button>
                                                    </form></li>
                                                    {% if request.user.is_authenticated %}
                                                    <li><form action="{% url "goods:add_love" id=game.id pk=request.user.id %}" method="post">
                                                        {% csrf_token %}
                                                        <button class="btn btn-white bg-white btn-md" style="border-radius: 0;">
                                                        <i class="fas fa-heart"></i>
                                                        </button>
                                                    </form></li>
                                                    {% endif %}
                                                    <li><a href="#"><i class="fas fa-plus"></i></a></li>
                                                    <li><a href="{% url "goods:profile" pk=game.id %}"><i class="fas fa-expand"></i></a></li>
                                            </ul>
                                    </div>
                                    <div class="part-2">
                                            <h3 class="product-title"><a href="{% url "goods:profile" pk=game.id %}">{{ game.name }}</a></h3>
                                            <h4 class="product-price">{{ game.price }}₽</h4>
                                    </div>
                            </div>
                    </div>
                    {% endfor %}
                    
            </div>
            {% endif %}
    </div>
</section>
{% if page_obj.paginator.count > 8 %}
<nav class="pagination-outer" aria-label="Page navigation">
        <ul class="pagination">
                {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                </a>
            </li>
            {% endif %}
                {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-item active"><a class="page-link" href="?page={{ p }}">{{p}}</a></li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{p}}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                    <span aria-hidden="true">»</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
{% endblock full_content %}

templates/goods/index_love.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block nav_love%}
active 
{% endblock %}

{% block full_content %}
<section class="pt-5 pb-5">
    <div class="container">
      <div class="row w-100">
          <div class="col-lg-12 col-md-12 col-12">
              <h3 class="display-5 mb-2 text-center">Избранное</h3>
                  {% if len == 0 %}
                  <h1>
                    В избранном пусто
                  </h1>
                  {% else %}
              <table id="shoppingCart" class="table table-condensed table-responsive">
                  <thead>
                      <tr>
                          <th style="width:60%">Товар</th>
                          <th style="width:12%">Цена</th>
                          <th style="width:16%"></th>
                      </tr>
                  </thead>
                  <tbody>
                    {% for product in favor %}
                      <tr>
                          <td data-th="Product">
                              <div class="row">
                                  <div class="col-md-3 text-left">
                                      <img src="{{ product.photos.first.image.url }}" alt="" class="img-fluid d-none d-md-block rounded mb-2 shadow ">
                                  </div>
                                  <div class="col-md-9 text-left mt-sm-2">
                                    {% if product.get_model.is_game %}
                                      <h4><a href='{% url "goods:profile" pk=product.id %}'>{{ product.name }}</a></h4>
                                      {% else %}
                                      <h4><a href='{% url "goods:console" pk=product.id %}'>{{ product.name }}</a></h4>
                                      {% endif %}
                                      <p class="font-weight-light"></p>
                                  </div>
                              </div>
                          </td>
                          <td data-th="Price">{{ product.price }}₽</td>
                          <td class="actions" data-th="">
                              <div class="text-right">
                                
                                  <form action="{% url "goods:remove_love" id=product.id pk=request.user.id %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-white border-secondary bg-white btn-md mb-2">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                              </div>
                          </td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>
              {% endif %}
          </div>
      </div>
      <div class="row mt-4 d-flex align-items-center">
        <div class="col-sm-6 mb-3 mb-m-1 order-md-1 text-md-left">
            <a href="{% url "goods:main" %}">
                <i class="fas fa-arrow-left mr-2"></i> Начать покупки</a>
        </div>
    </div>
  </div>
  </section>
  {% endblock %}

templates/goods/profile.html
{% extends "goods/goods.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block full_content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{game.photos.all.first.image.url}}" alt="..."></div>
            <div class="col-md-6">
                <div class="small mb-1">id: {{ game.id }}</div>
                <h1 class="display-5 fw-bolder" style="font-size: 40px;">{{ game.name }}</h1>
                <div class="fs-5 mb-5">
                    <span>{{ game.price }}₽</span>
                </div>
                <p class="lead">{{ game.description }}</p>
                <p class="lead">Игра для консоли - {{ game.model_console.name }}</p>
                <p class="lead">Разработчик - {{ game.developer.name }}</p>
                <p class="lead">Жанр - 
                    {{ cat }}
                </p>
                <div class="d-flex">
                    <form action="{% url "cart:add" id=game.id %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Добавить в корзину
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/goods/profile_console.html
{% extends "goods/goods.html" %}
{% load bootstrap5 %}
{% load bootstrap %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block full_content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{console.photos.all.first.image.url}}" alt="..."></div>
            <div class="col-md-6">
                <div class="small mb-1">id: {{ console.id }}</div>
                <h1 class="display-5 fw-bolder" style="font-size: 40px;">{{ console.name }}</h1>
                <div class="fs-5 mb-5">
                    <span>{{ console.price }}₽</span>
                </div>
                <p class="lead">{{ console.description }}</p>
                <div class="d-flex">
                    <form action="{% url "cart:add" id=console.id %}" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Добавить в корзину
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}