imag/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

imagazine/cart/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('add/<int:id>/', AddProductCartView.as_view(), name='add'),
    path('remove/<int:id>/', RemoveProductCart.as_view(), name='remove'),
    path('', IndexCart.as_view(), name='index'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('payment/api/', YoomoneyNotifView.as_view(), name='notif'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('orders/<int:pk>/', OrderView.as_view(), name='order')
]

imagazine/goods/urls.py
from django.urls import path, include
from imagazine.goods.views import *

urlpatterns = [ 
               path('', IndexView.as_view(), name='main'),
               path('games/', GamesIndexView.as_view(), name='index'),
               path('console/', ConsolesView.as_view(), name='consoles_index'),
               path('console/<int:pk>/', ConsoleView.as_view(), name='console'),
               path('games/<int:pk>/', ProfileGameView.as_view(), name='profile'),
               path('love/<int:pk>/', LoveIndexView.as_view(), name='loves'), 
               path('love/remove/<int:pk>/<int:id>/', RemoveLoveView.as_view(), name='remove_love'),
               path('love/add/<int:pk>/<int:id>/', LoveAddView.as_view(), name='add_love')
               ]

imagazine/urls.py
from django.contrib import admin
from django.urls import path, include
from imagazine.views import MainView, AboutView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('users/', include(('imagazine.users.urls', 'users'), namespace='users')),
    path('goods/', include(('imagazine.goods.urls', 'goods'), namespace='goods')),
    path('cart/', include(('imagazine.cart.urls', 'cart'), namespace='cart'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #new

imagazine/users/urls.py
from django.urls import path
from imagazine.users.views import *
from django.views.generic.base import TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('create/', CreateUserView.as_view(), name='create'),
    path('logout/', logout_user, name='logout'),
    path('activate/<str:uid64>/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('activate/email-confirmation-sent/', TemplateView.as_view(template_name='users/email_confirmation_sent.html'), name='email_confirmation_sent'),
    path('activate/email-not-confirm/', TemplateView.as_view(template_name='users/email_not_confirm.html'), name='email_not_confirm'),
    path('<int:pk>/', ProfileUserView.as_view(), name='profile_user'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html', email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('<int:pk>/delete/', DeleteUserView.as_view(), name='delete'),
    path('<int:pk>/update/', UpdateUserView.as_view(), name='update'),
]

templates/base.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block nav_main%}
active
{% endblock %}

{% block content %}
<div class="text-center border-bottom" style="
position: absolute;
bottom:0;
">
  <h1 class="display-4 fw-bold text-body-emphasis">Imag</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      Добро пожаловать в наш интернет-магазин игровых консолей и игр! У нас вы найдете широкий ассортимент игровых консолей, от последних моделей до классических платформ, а также огромный выбор популярных игр для всех возрастов и жанров.
    </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
      <form action="{% url "users:login" %}">
      <button type="submit" class="btn btn-primary btn-lg px-4 me-sm-3">Войти</button>
      </form>
      <form action="{% url "goods:main" %}">
      <button type="submit" class="btn btn-outline-secondary btn-lg px-4">Товары</button>
      </form>
    </div>
  </div>
  <div class="overflow-hidden" style="max-height: 30vh;">
    <div class="container px-5">
      <img src="{% static "img/con1.jpeg" %}" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
    </div>
  </div>
</div>
{% endblock content %}

templates/hb.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block nav_about%}
active
{% endblock %}

{% block content %}
<h1>
    С ДНЕМ РОЖДЕНИЯ!!!
</h1>
<h5>
    от developera
</h5>
{% endblock content %}

templates/main.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8" />
  <title>{{ title }}</title>
  {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script>
      $(document).ready(function(){
          $('input').addClass('form-control');
      });
  </script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />

    <link href="https://getbootstrap.com/docs/5.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Favicons -->
    <link rel="manifest" href="https://getbootstrap.com/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="icon" href="{% static "img/controller.svg" %}">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="{% static "css/sidebars.css" %}" rel="stylesheet">
    {% block head %}{% endblock head %}
 </head>
 <body>
    <div class="d-flex flex-column flex-shrink-0 p-3 bg-body-tertiary" style="width: 280px; position: fixed!important; height: 100%;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none" previewlistener="true">
            <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"/>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -2 12 20" width="100%" height="100%">
                <path d="M11.5 6.027a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m2.5-.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-1.5 1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m-6.5-3h1v1h1v1h-1v1h-1v-1h-1v-1h1v-1"/>
                <path d="M3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .62.39c.655-.079 1.35-.117 2.043-.117.72 0 1.443.041 2.12.126a.5.5 0 0 1 .622-.399l1.932.518a.5.5 0 0 1 .306.729c.14.09.266.19.373.297.408.408.78 1.05 1.095 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.816-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773-.245-.232-.496-.526-.739-.808-.126-.148-.25-.292-.368-.423-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.423-.243.282-.494.575-.739.808-.398.38-.877.706-1.513.773a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772a2.34 2.34 0 0 1 .433-.335.504.504 0 0 1-.028-.079zm2.036.412c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.504C4.861 9.969 5.978 9.027 8 9.027s3.139.942 3.965 1.855c.164.181.307.348.44.504.214.251.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z"/>
              </svg></svg>
          <span class="fs-4">Imag</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
          <li class="nav-item">
            <a href="{% url "main" %}" class="nav-link {% block nav_main%}link-body-emphasis{% endblock %}" aria-current="page">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"><svg id="home" viewBox="0 0 16 16" width="100%" height="100%">
                <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5z"></path>
              </svg></use></svg>
              Главная
            </a>
          </li>
          <li>
            <a href="#" class="nav-link {% block nav_top_sales%}link-body-emphasis{% endblock %}">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"><svg id="speedometer2" viewBox="0 0 16 16" width="100%" height="100%">
                <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"></path>
                <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"></path>
              </svg></use></svg>
              Топ продаж
            </a>
          </li>
          <li>
            <a href="{% url "cart:orders" %}" class="nav-link {% block nav_orders%}link-body-emphasis{% endblock %}">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"><svg id="table" viewBox="0 0 16 16" width="100%" height="100%">
                <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"></path>
              </svg></use></svg>
              Заказы
            </a>
          </li>
          <li>
            {% if request.user.is_authenticated %}
            <a href="{% url "goods:loves" pk=request.user.id %}" class="nav-link {% block nav_love%}link-body-emphasis{% endblock %}">
              <svg class="bi pe-none me-2" width="16" height="16"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
              </svg></svg>
              Избранное
            </a>
            {% endif %}
          </li>
          <li>
            <a href="{% url "cart:index" %}" class="nav-link {% block nav_cart%}link-body-emphasis{% endblock %}">
              <svg class="bi pe-none me-2" width="16" height="16"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
              </svg></svg>
              Корзина
            </a>
          </li>
          <li>
            <a href="{% url "goods:main" %}" class="nav-link {% block nav_goods%}link-body-emphasis{% endblock %}">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"><svg id="grid" viewBox="0 0 16 16" width="100%" height="100%">
                <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"></path>
              </svg></use></svg>
              Товары
            </a>
          </li>
          <li>
            <a href="{% url "about" %}" class="nav-link {% block nav_about%}link-body-emphasis{% endblock %}">
              <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"><svg id="people-circle" viewBox="0 0 16 16" width="100%" height="100%">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
              </svg></use></svg>
              О нас
            </a>
          </li>
        </ul>
        <hr>
        <div class="dropdown">
          {% if request.user.is_authenticated %}
          <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{ request.user.photo.url }}" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>Пользователь</strong>
          </a>
          <ul class="dropdown-menu text-small shadow" style="">
            <li><a class="dropdown-item" href="{% url "users:profile_user" pk=request.user.id %}">Профиль</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "users:logout" %}">Выйти</a></li>
          </ul>
          {% else %}
          <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static "img/img_avatar.png" %}" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>Пользователь</strong>
          </a>
          <ul class="dropdown-menu text-small shadow" style="">
            <li><a class="dropdown-item" href="{% url "users:login" %}">Войти</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url "users:create" %}">Зарегистрироваться</a></li>
          </ul>
          {% endif %}
        </div>
      </div>
    <div style="margin-left: 280px;">
      {% if messages %}
          <div class="messages">
              {% for message in messages %}
              <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} style="text-align: center;">{{ message }}</div>
              {% endfor %}
          </div>
          {% endif %}
        {% block full_content %}
        <div class='center'>
        {% block content %}{% endblock content %}
        </div>
        {% endblock full_content %}
    </div>
 </body>
</html>