imag/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

imagazine/urls.py
from django.contrib import admin
from django.urls import path, include
from imagazine.views import MainView, AboutView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('users/', include(('imagazine.users.urls', 'users'), namespace='users')),
    path('goods/', include(('imagazine.goods.urls', 'goods'), namespace='goods')),
    path('cart/', include(('imagazine.cart.urls', 'cart'), namespace='cart'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #new

imagazine/users/urls.py
from django.urls import path
from imagazine.users.views import *
from django.views.generic.base import TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('create/', CreateUserView.as_view(), name='create'),
    path('logout/', logout_user, name='logout'),
    path('activate/<str:uid64>/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('activate/email-confirmation-sent/', TemplateView.as_view(template_name='users/email_confirmation_sent.html'), name='email_confirmation_sent'),
    path('activate/email-not-confirm/', TemplateView.as_view(template_name='users/email_not_confirm.html'), name='email_not_confirm'),
    path('<int:pk>/', ProfileUserView.as_view(), name='profile_user'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html', email_template_name='users/password_reset_email.html', success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('<int:pk>/delete/', DeleteUserView.as_view(), name='delete'),
    path('<int:pk>/update/', UpdateUserView.as_view(), name='update'),
]

imagazine/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagazine.goods.models import Goods


class User(AbstractUser):
    username = models.TextField(blank=True, null=True, unique=False)
    photo = models.ImageField(blank=True, null=True, upload_to='images/', default='images/img_avatar.png', verbose_name="Фото")
    date_of_birth = models.DateField()
    favor = models.ManyToManyField(Goods, blank=True, null=True, related_name='user')

imagazine/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from imagazine.users.models import User

class UserAuthForm(AuthenticationForm):
    username = forms.CharField(label='Почта', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ['email',
                  'password'
                  ]
        
class UserCreateForm(UserCreationForm):
    email = forms.CharField(label='Почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    date_of_birth = forms.DateField(label='Дата рождения', widget=forms.DateInput(attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'}))
    photo = forms.ImageField(label='Фото', required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = User
        fields = ['email',
                  'date_of_birth',
                  'photo', 
                  'password1', 'password2']
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            if User.objects.get(email=email).is_active == True:
                raise forms.ValidationError("Такой E-mail уже существует!")
            else:
                User.objects.get(email=email).delete()
        return email
    
class UserUpdateForm(forms.ModelForm):
    photo = forms.ImageField(label='Фото', required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))
    
    class Meta:
        model = User
        fields = [
                  'photo']

imagazine/users/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView
from imagazine.users.forms import *
from imagazine.users.models import User
from django.contrib.auth import logout
from django.contrib.auth.tokens import default_token_generator
from django.contrib import messages
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.models import Site
from django.core.mail import send_mail
from django.views.generic.detail import DetailView
from .mixins import RightUserMixin
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class LoginUserView(SuccessMessageMixin, LoginView):
    success_url = reverse_lazy('main')
    login_url = reverse_lazy('users:login')
    success_message = 'Вы авторизованы'
    form_class = UserAuthForm
    template_name = 'users/login.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Вход'
        return context
    
    
class CreateUserView(SuccessMessageMixin, CreateView):
    success_message = 'Пользователь создан'
    success_url = reverse_lazy('users:login')
    form_class = UserCreateForm
    # fields = ['username', 'password1', 'password2', 'photo', 'date_of_birth']
    template_name = 'users/create.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Регистрация'
        return context
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uid64': uid, 'token': token})
        current_site = Site.objects.get_current().domain
        send_mail(
            'Подтвердите свой электронный адрес',
            f'Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: http://{current_site}{activation_url}',
            'faridylkaaa@yandex.ru',
            [user.email],
            fail_silently=False,
        )
        return redirect(reverse_lazy('users:email_confirmation_sent'))
    
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, 'Пользователь вышел')
        return redirect(reverse_lazy('main'))
    else:
        messages.info(request, 'Вы не авторизованы')
        return redirect(reverse_lazy('users:login'))
    
class ConfirmEmailView(View):
    def get(self, request, uid64, token):
        try:
            uid = urlsafe_base64_decode(uid64)
            user = User.objects.get(pk=uid)
        except (ValueError, TypeError, OverflowError, User.DoesNotExist):
            user = None
        
        if user and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Почта подтверждена')
            return redirect(reverse_lazy('users:login'))
        else:
            return redirect(reverse_lazy('users:email_not_confirm'))
        
class ProfileUserView(RightUserMixin, DetailView):
    model = User
    template_name = 'users/profile.html'
    
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль'
        return context
    
class DeleteUserView(LoginRequiredMixin, SuccessMessageMixin, RightUserMixin, DeleteView):
    model = User
    template_name = 'users/delete.html'
    success_message = 'Пользователь удален'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('main')
    
class UpdateUserView(LoginRequiredMixin, RightUserMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'users/update.html'
    success_message = 'Пользователь изменен'
    login_url = reverse_lazy('users:login')
    success_url = reverse_lazy('main')

templates/users/create.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
<h1>
    Регистрация
</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Создать</button></p>
</form>
</div>
{% endblock content %}

templates/users/delete.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
<h1>
    Удаление пользователя
</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-danger">Удалить</button></p>
</form>
</div>
{% endblock content %}

templates/users/email_confirmation_sent.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<h1>
    Письмо отправлено на вашу почту
</h1>
{% endblock content %}

templates/users/email_not_confirm.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<h1>
    Почта не была подтверждена ( аккаунт не активирован )
</h1>
{% endblock content %}

templates/users/login.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div class="text-center border-bottom center">
<form method="post">
    <h1 class="h3 mb-3 fw-normal">Вход</h1>
    {% csrf_token %}
    <div class="form-error">
        {{ form.non_field_errors }}
    </div>
    {% for f in form %}
    <div class='form-floating'>
        {{ f }}
        <label class="form-label" for="{{ f.id_for_label }}">{{f.label}}:</label>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Войти</button>
</form>
</div>
{% endblock content %}

templates/users/password_reset_complete.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
<h1>
    Пароль изменен
</h1>
<p>
    Вы можете прямо сейчас войти под новым паролем
<form action="{% url "users:login" %}">
    <p><button type="submit" class="btn btn-primary">Перейти</button></p>
</form>
</div>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
<h1>
    Изменение пароля
</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Изменить</button></p>
</form>
</div>
{% endblock content %}

templates/users/password_reset_done.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
<h1>
    Инструкции отправлены на вашу почту
</h1>
{% endblock content %}

templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your email, in case you’ve forgotten:' %} {{ user.email }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/users/password_reset_form.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
<h1>
    Изменение пароля
</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Изменить</button></p>
</form>
</div>
{% endblock content %}

templates/users/profile.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
    <div class="card">
        <img src="{{ request.user.photo.url }}" alt="Avatar" style="width:100%">
        <div class="container">
          <h4 style="
          margin: 10px 0;"><b>{{ object.email }}</b></h4>
          <form action="{% url "users:update" pk=request.user.id %}" style="
          margin: 10px 0;">
            <button type="submit" class="btn btn-primary" style="margin:0 10px;">Изменить</button>
        </form>
        <form action="{% url "users:delete" pk=request.user.id %}" style="
          margin: 10px 0;">
            <button type="submit" class="btn btn-danger" style="margin:0 10px;">Удалить</button>
        </form>
        </div>
      </div>
</div>
{% endblock content %}

templates/users/update.html
{% extends "main.html" %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}
<div style='width: 40%;'>
<h1>
    Изменение пользователя
</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-primary">Изменить фото</button></p>
    
</form>
<form action="{% url "users:password_reset" %}" style="">
            <button type="submit" class="btn btn-warning" style="margin:0 10px;">Изменить пароль</button>
        </form>
</div>
{% endblock content %}